#if !canImport(ObjectiveC)
import XCTest

extension KeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyTests = [
        ("testDefault", testDefault),
        ("testGet", testGet),
        ("testIncorrectType", testIncorrectType),
        ("testRemove", testRemove),
        ("testSet", testSet),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KeyTests.__allTests__KeyTests),
    ]
}
#endif
